name: Build and Deploy

on:
  push:
    branches:
      - main  # Agora ele pode rodar em pushes na main também
    tags:
      - '*'

env:
  REGISTRY: ${{ vars.DOCKERHUB_HOST }}
  BASE_IMAGE: ctezlifrn/avamoodlebase
  MAIN_IMAGE: ctezlifrn/avamoodle

jobs:
  # Detecta mudanças na pasta /base
  detect-base-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check changes
        id: changes
        run: |
          # Verifica se é o primeiro commit ou se houve alteração na pasta base
          if git rev-parse --verify HEAD^1 >/dev/null 2>&1; then
            if git diff --quiet HEAD^1 HEAD -- base/; then
              echo "base=false" >> $GITHUB_OUTPUT
            else
              echo "base=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "base=true" >> $GITHUB_OUTPUT
          fi
    outputs:
      base_changed: ${{ steps.changes.outputs.base }}

  # Build e Push da Imagem Base
  build-base:
    needs: detect-base-changes
    if: needs.detect-base-changes.outputs.base_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./base
          push: true
          # Usando os primeiros 7 caracteres do SHA
          tags: ${{ env.REGISTRY }}/${{ env.BASE_IMAGE }}:${{ github.sha }}

  # Build e Push da Imagem Principal
  build-main:
    needs: build-base
    if: always() && (needs.build-base.result == 'success' || needs.build-base.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./main
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.MAIN_IMAGE }}:${{ github.sha }}
          build-args: |
            AVA_IMAGE_VERSION=${{ github.sha }}

  # Deploy Kubernetes via Helm
  deploy-k8s:
    needs: build-main
    if: always() && needs.build-main.result == 'success'
    runs-on: [self-hosted, runner-dead]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 10.22.1.208 >> ~/.ssh/known_hosts

      - name: Enviar Chart do Helm
        run: |
          ssh root@10.22.1.208 "rm -rf /tmp/moodle-chart"
          scp -r ./helm root@10.22.1.208:/tmp/moodle-chart

      - name: Deploy via Helm no Goslar
        run: |
          echo "🚀 Deploying commit SHA: ${{ github.sha }}"
          
          ssh root@10.22.1.208 "helm upgrade --install moodle-ava /tmp/moodle-chart \
            --namespace ava \
            --set image.tag=${{ github.sha }} \
            --set image.repository=${{ env.MAIN_IMAGE }}"